apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: health-postgres-pvc
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 20Gi
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: health-postgres
spec:
  serviceName: health-postgres
  replicas: 1
  selector:
    matchLabels:
      app: health-postgres
  template:
    metadata:
      labels:
        app: health-postgres
    spec:
      containers:
        - name: postgres
          image: postgres:15-alpine
          env:
            - name: POSTGRES_DB
              value: health
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: health-secrets
                  key: postgres-user
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: health-secrets
                  key: postgres-password
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: health-postgres-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: health-postgres
spec:
  selector:
    app: health-postgres
  ports:
    - port: 5432
      targetPort: 5432
